### ISSUE TITLE
Dry ground can be destroyed instantly.

### ISSUE THREAD

**Issue by rvveber** [Nuparu00/7-Days-to-Mine-Mod#1]
Not sure if thats how its supposed to be since even dead bushes take some time to destroy.

![image](https://user-images.githubusercontent.com/8644906/108609530-c45fc500-73ce-11eb-955b-fd1d290a866a.png)

**Comment by Nuparu00** [comment]
I see, did not call Block#setHardness(). It will be fixed in the next version (along with the sound).
