### ISSUE TITLE
[Request] [Mod-Compat] Heat and Thirst <-> Tough as Nails

### ISSUE THREAD

**Issue by rvveber** [Nuparu00/7-Days-to-Mine-Mod#2]
It looks like temperature has not been added yet.
here is a suggestion, if you are thinking about adding it:

Check the presence of the Tough as Nails mod, and if it is available interact with its API to synchronize between 
their data and and add data via your events.
Source for the API can be found here: https://github.com/Glitchfiend/ToughAsNails

So that drinks from 7 days to mine would fill the thirst meter of though as nails, and armor or biomes would interact with the heatmeter. 

![image](https://user-images.githubusercontent.com/8644906/108610156-c11b0800-73d3-11eb-929b-82a20ed0c048.png)

**Comment by Nuparu00** [comment]
I take it this would also mean removing the thirst system my mod uses, right?

**Comment by Nuparu00** [comment]
I see that TAN has a file in the config folder called drink_stats.json, where you can specify what items are drinkable and their hydration value, poison chances, etc... There are also similar files for blocks and armors.
So the best thing would be having an option in my config to disable my thirst system and then let players add the modded items/blocks to these files.

**Comment by rvveber** [comment]
That sounds great! 👍
